// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ChatWhatsapp: typeof import('./src/components/ChatWhatsapp.vue')['default']
    ConsultDetails: typeof import('./src/components/gtconsultas/ConsultDetails.vue')['default']
    ContentBox: typeof import('./src/components/ContentBox.vue')['default']
    GeralAlert: typeof import('./src/components/GeralAlert.vue')['default']
    GeralButton: typeof import('./src/components/buttons/GeralButton.vue')['default']
    GeralInput: typeof import('./src/components/GeralInput.vue')['default']
    GeralModal: typeof import('./src/components/GeralModal.vue')['default']
    HistoryButtons: typeof import('./src/components/buttons/HistoryButtons.vue')['default']
    LayoutSidebar: typeof import('./src/components/layout/LayoutSidebar.vue')['default']
    LogoutButton: typeof import('./src/components/buttons/LogoutButton.vue')['default']
    ModalImport: typeof import('./src/components/ModalImport.vue')['default']
    NcmConsult: typeof import('./src/components/gtconsultas/NcmConsult.vue')['default']
    ProfileDropdown: typeof import('./src/components/ProfileDropdown.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaxProfile: typeof import('./src/components/TaxProfile.vue')['default']
    TaxProfileInfo: typeof import('./src/components/TaxProfileInfo.vue')['default']
    TaxRemittee: typeof import('./src/components/TaxRemittee.vue')['default']
  }
}
